percona/percona-everest-frontend

- apps/everest/app.tsx
https://tanstack.com/query/v3/docs/react/devtools
> Added ReactQueryDevtools

- apps/everest/everest.react-app.ts
Structure:
```
/assets-manifest.json
/favicon.ico
/index.html
/static
- main.ef374123ece8e3462095.js
```
> chore: serve assets in static folder

- apps/everest/components/main/Main.tsx
- pnpm-lock.yaml
https://jira.percona.com/browse/EVEREST-212
> EVEREST-212 fix layout issue

- .github/workflows/ci.yml
- apps/everest/everest.react-app.ts
https://github.com/percona/percona-everest-backend/commit/16b822af85ab5f674f2d8bbf653b1f9219fed030
> Default port changed to 8080

- apps/everest/pages/settings/storage-locations/createEditModal/create-edit-modal.tsx
- apps/everest/pages/settings/storage-locations/storage-locations.messages.ts
- apps/everest/pages/settings/storage-locations/storage-locations.tsx
Added no data message, uncomment description field
> Backups storages fix

- apps/everest/components/delete-dialog/delete-dialog.tsx
- apps/everest/pages/settings/storage-locations/storage-locations.messages.ts
- apps/everest/pages/settings/storage-locations/storage-locations.tsx
https://jira.percona.com/browse/EVEREST-285
> EVEREST-285 Confirm delete modal

- apps/everest/components/db-cluster-view/DbClusterView.tsx
- apps/everest/components/db-cluster-view/dbClusterView.messages.ts
https://jira.percona.com/browse/EVEREST-285
> EVEREST-285 Added delete modal to DbClusterView

- apps/everest/api/restores.ts
- apps/everest/components/confirm-dialog/confirm-dialog.tsx
- apps/everest/components/confirm-dialog/confirm-dialog.types.ts
- apps/everest/components/db-cluster-view/DbClusterView.tsx
- apps/everest/hooks/api/restores/useDbClusterRestore.ts
- apps/everest/pages/backups/backups-list/backups-list.messages.ts
- apps/everest/pages/backups/backups-list/backups-list.tsx
- apps/everest/pages/settings/storage-locations/storage-locations.tsx
- apps/everest/types/restores.types.ts
https://jira.percona.com/browse/EVEREST-246
> EVEREST-246-restore-to-same-cluster

- apps/everest/pages/settings/storage-locations/createEditModal/create-edit-modal.tsx
- tsconfig.json
> EVEREST-290-hiding-azure-and-google-storage-types: hiding extra options

- apps/everest/components/db-cluster-view/DbClusterView.tsx
- apps/everest/hooks/api/db-cluster/useCreateDbCluster.ts
- apps/everest/hooks/api/db-cluster/useUpdateDbCluster.ts
- apps/everest/pages/database-form/database-form.types.ts
- apps/everest/pages/database-form/database-preview/database-preview.test.tsx
- apps/everest/pages/database-form/database-preview/database.preview.messages.ts
- apps/everest/pages/database-form/database-preview/sections/index.tsx
- apps/everest/pages/database-form/steps/index.ts
- apps/everest/pages/database-form/useDatabaseFormDefaultValues.ts
- apps/everest/ui-tests/tests/create-db-cluster.e2e.ts
k8s and backups columns were removed
backups step was removed
> EVEREST-334-hide-backup-step-dbwizard

- apps/everest/hooks/api/restores/useDbClusterRestore.ts
- apps/everest/pages/database-form/database-form.tsx
- apps/everest/pages/database-form/restore-dialog/restore-dialog.messages.ts
- apps/everest/pages/database-form/restore-dialog/restore-dialog.tsx
- apps/everest/pages/database-form/restore-dialog/restore-dialog.types.ts
- apps/everest/pages/database-form/useDatabaseFormDefaultValues.ts
- apps/everest/types/restores.types.ts
[restore fix.webm](https://github.com/percona/percona-everest-frontend/assets/90199600/c146bc23-dd0e-41be-95ac-f13acd590376)
> EVEREST-350 Changed text, added default restore to name

- apps/everest/pages/database-form/steps/fifth/fifth-step.messages.ts
- apps/everest/pages/database-form/steps/fifth/fifth-step.tsx
- ui-lib/form/inputs/switch/switch.tsx
- ui-lib/form/inputs/switch/switch.types.ts
[monitoring empty issue fix.webm](https://github.com/percona/percona-everest-frontend/assets/90199600/a3137e20-58d3-437e-a24a-e045941334d2)
> Everest 210 monitoring step

- apps/everest/pages/database-form/restore-dialog/restore-dialog.messages.ts
> EVEREST-350-incorrect-command-in-last-step: fix the namespace

- apps/everest/components/db-cluster-view/expandedRow/ExpandedRow.tsx
[password issue.webm](https://github.com/percona/percona-everest-frontend/assets/90199600/57ad6b96-9ffd-495f-b744-11311eeeef99)
> EVEREST-363-password-copy-issue: fix click to password

- apps/everest/components/drawer/Drawer.constants.ts
- apps/everest/everest.app-root.tsx
- apps/everest/pages/settings/settings.types.ts
> Hide setting tabs

- apps/everest/pages/backups/backups-list/backups-list.tsx
> EVEREST-366-disabling-new-db-option-for-failed-backups: disabling

- apps/everest/pages/database-form/database-form.types.ts
> EVEREST-271-db-name-validation: add validation of first number

- apps/everest/types/backups.types.ts
https://jira.percona.com/browse/EVEREST-437
> EVEREST-437 Rename backup status from OK to succeeded

- apps/everest/pages/database-form/steps/sixth/sixth-step.messages.ts
- apps/everest/pages/database-form/steps/sixth/sixth-step.tsx
- apps/everest/ui-tests/tests/db-cluster/create-db-cluster/create-db-cluster.e2e.ts
https://jira.percona.com/browse/EVEREST-331
> Everest 331 edit message

- .github/workflows/rc.yml
EVEREST-428 
Rebuild RC image on every commit to the release branch
> EVEREST-428 rebuild RC image

- apps/everest/components/welcome-dialog/welcome-dialog.messages.ts
- apps/everest/components/welcome-dialog/welcome-dialog.tsx
> EVEREST-455-welcome-message-fix: fix text

- apps/everest/components/db-cluster-view/DbClusterView.tsx
- apps/everest/pages/backups/backups-list/backups-list.tsx
https://jira.percona.com/browse/EVEREST-461
> fix: close modal after DB deletion

- apps/everest/pages/databases/no-kubernetes/no-kubernetes.messages.ts
- apps/everest/pages/databases/no-kubernetes/no-kubernetes.tsx
> EVEREST-454-no-k8s-cluster-screen: fix text

- apps/everest/components/db-cluster-view/DbClusterView.constants.ts
- apps/everest/components/db-cluster-view/DbClusterView.utils.ts
- apps/everest/components/db-cluster-view/dbClusterView.messages.ts
- apps/everest/types/dbCluster.types.ts
https://jira.percona.com/browse/EVEREST-393
> Restoring status should not be "Unknown"

- apps/everest/pages/backups/on-demand-backup-modal/on-demand-backup-modal.types.ts
https://jira.percona.com/browse/EVEREST-362
> Improve error message on backup modal

- apps/everest/pages/backups/on-demand-backup-modal/on-demand-backup-modal.types.ts
- apps/everest/pages/database-form/steps/advanced-configurations/advanced-configurations.utils.ts
> EVEREST-407-db-engine-configuration: changing text

- apps/everest/app.tsx
- apps/everest/components/db-cluster-view/DbClusterView.test.tsx
- apps/everest/components/db-cluster-view/DbClusterView.tsx
- apps/everest/components/db-cluster-view/dbClusterView.messages.ts
- apps/everest/components/db-cluster-view/dbClusterView.types.ts
- apps/everest/hooks/api/db-clusters/useDbClusters.ts
- apps/everest/pages/databases/databases.tsx
https://jira.percona.com/browse/EVEREST-306
> Everest-306: remove duplicate notifications

- apps/everest/components/form-dialog/form-dialog.spec.tsx
- apps/everest/components/form-dialog/form-dialog.tsx
https://jira.percona.com/browse/EVEREST-360
> EVEREST-360 dialog focus

- apps/everest/components/code-copy-block/code-copy-block.tsx
- apps/everest/components/form-dialog/form-dialog.tsx
- apps/everest/components/form-dialog/form-dialog.types.ts
- apps/everest/components/switch-outlined-box/switch-oulined-box.tsx
- apps/everest/contexts/drawer/drawer.context.tsx
- apps/everest/hooks/utils/useActiveBreakpoint.ts
- apps/everest/pages/database-form/database-form.tsx
- apps/everest/pages/database-form/database-preview/preview-section.tsx
- apps/everest/pages/database-form/steps/second/second-step.tsx
- apps/everest/pages/databases/no-kubernetes/no-kubernetes.tsx
- apps/everest/pages/settings/default-configurations/default-configurations.tsx
New useActiveBreakpoint hook for easier work with breaking points.
> Unite active breaking points

- apps/everest/pages/db-cluster-details/backups/no-storages-modal/no-storages-modal.tsx
- apps/everest/pages/db-cluster-details/backups/no-storages-modal/no-storages-modal.type.ts
- apps/everest/pages/db-cluster-details/backups/on-demand-backup-modal/on-demand-backup-modal.tsx
- apps/everest/pages/db-cluster-details/backups/scheduled-backup-modal/scheduled-backup-modal.tsx
- apps/everest/pages/db-cluster-details/db-cluster-details.messages.ts
https://jira.percona.com/browse/EVEREST-487
> EVEREST-487 No storage location modal

- ui-lib/table/table.tsx
https://jira.percona.com/browse/EVEREST-562
> Disabled auto reset with new data

- apps/everest/pages/db-cluster-details/backups/backups.tsx
- apps/everest/pages/db-cluster-details/cluster-overview/cluster-overview.tsx
- apps/everest/pages/db-cluster-details/db-cluster-details.tsx
- apps/everest/ui-tests/tests/no-match/no-match.e2e.ts
https://jira.percona.com/browse/EVEREST-451
Not showing the 404 page for wrong backup URL was returned by testers as a bug. After a discussion with Nuna, I uncommented the fix for this previously created and fixed a fetch error issue.
> EVEREST-451 uncommented no match url fix

- apps/everest/pages/database-form/database-form.constants.ts
- apps/everest/pages/database-form/database-preview/preview-section.tsx
- apps/everest/pages/database-form/steps/first/first-step.tsx
- apps/everest/pages/database-form/steps/first/first-steps.constants.ts
- apps/everest/pages/database-form/steps/second/second-step.const.ts
- apps/everest/pages/database-form/steps/second/second-step.tsx
- apps/everest/ui-tests/tests/db-cluster/create-db-cluster/create-db-cluster.e2e.ts
- apps/everest/ui-tests/tests/db-cluster/create-db-cluster/steps/resources-step.ts
https://jira.percona.com/browse/EVEREST-536
> EVEREST-536: change default nodes

- apps/everest/components/db-cluster-view/DbClusterView.tsx
https://jira.percona.com/browse/EVEREST-326
> EVEREST-326 Changed suspend logic

- apps/everest/vite.config.ts
Auto open browser when running make dev
> One small step for man, one giant leap for developers

- Makefile
- README.md
- apps/everest/move-build.js
Improve README file.
Targets https://github.com/percona/percona-everest-frontend/issues/154
> chore: improve readme

- apps/everest/package.json
- apps/everest/src/App.tsx
- packages/design/package.json
- packages/design/src/themes/base/BaseTheme.tsx
- pnpm-lock.yaml
https://jira.percona.com/browse/EVEREST-634
> Everest-634: date picker

- apps/everest/src/pages/db-cluster-details/backups/scheduled-backup-modal/scheduled-backup-modal-form/scheduled-backup-modal-form.types.ts
https://jira.percona.com/browse/EVEREST-581
> fix: bad error message on schedule name

- packages/ui-lib/src/copy-to-clipboard-button/CopyToClipboardButton.tsx
[ Warning text to be changed in the meanwhiie]
https://jira.percona.com/browse/EVEREST-641
> fix: check if Clipboard API is available

- apps/everest/src/App.tsx
- packages/design/src/theme-context-provider/index.ts
- packages/design/src/themes/base/BaseTheme.tsx
- packages/design/src/themes/base/BaseTheme.utils.ts
- packages/ui-lib/package.json
- packages/ui-lib/src/index.ts
- packages/ui-lib/src/notistack-mui-snackbar/NotistackMuiSnackbar.tsx
- packages/ui-lib/src/notistack-mui-snackbar/index.ts
- pnpm-lock.yaml
https://jira.percona.com/browse/EVEREST-456
> Correct colors for Alert

- packages/design/src/themes/base/BaseTheme.tsx
- packages/design/src/themes/base/BaseTheme.utils.ts
https://jira.percona.com/browse/EVEREST-649
> EVEREST-649 improve error colors

- apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
https://jira.percona.com/browse/EVEREST-707
> EVEREST-707 - Added redirect to dashboard after restore

- apps/everest/src/pages/databases/DbClusterView.tsx
- apps/everest/src/pages/databases/DbClusterView.utils.ts
- apps/everest/src/pages/databases/dbClusterView.messages.ts
- apps/everest/src/pages/databases/dbClusterView.types.ts
- apps/everest/src/pages/databases/expandedRow/ExpandedRow.tsx
https://perconadev.atlassian.net/browse/EVEREST-686
> feat: add number of nodes to table

- apps/everest/src/pages/database-form/steps/backups/backups.tsx
https://perconadev.atlassian.net/browse/EVEREST-718
> fix: check backup toggle touched state

- apps/everest/src/contexts/auth/auth.provider.tsx
- apps/everest/src/pages/db-cluster-details/db-cluster-details.messages.ts
https://perconadev.atlassian.net/browse/EVEREST-710
> Everest 710 login bad token message

- .github/workflows/ci.yml
- apps/everest/.e2e/utils/database-engines.ts
- apps/everest/src/api/monitoring.ts
- apps/everest/src/hooks/api/db-engines/useDbEngines.ts
- apps/everest/src/hooks/api/monitoring/useMonitoringInstancesList.ts
- apps/everest/src/pages/settings/monitoring-endpoints/createEditModal/create-edit-modal.tsx
- apps/everest/src/pages/settings/monitoring-endpoints/createEditModal/create-edit-modal.types.ts
- apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.messages.ts
- apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.tsx
- apps/everest/src/pages/settings/settings.types.ts
- apps/everest/src/router.tsx
- apps/everest/src/shared-types/dbEngines.types.ts
- apps/everest/src/shared-types/monitoring.types.ts
- apps/everest/src/utils/common-validation.ts
- apps/everest/src/utils/generalOptimisticDataUpdate.ts
https://perconadev.atlassian.net/browse/EVEREST-188
> Everest 188 monitoring endpoints

- apps/everest/.e2e/db-cluster/db-wizard/edit-db-cluster/pitr-step.e2e.ts
- apps/everest/.e2e/playwright.config.ts
- apps/everest/src/components/schedule-form/schedule-form.tsx
- apps/everest/src/pages/database-form/database-form.utils.ts
- apps/everest/src/pages/database-form/steps/backups/schedule-section/schedule-section.tsx
- apps/everest/src/pages/db-cluster-details/backups/scheduled-backup-modal/scheduled-backup-modal-form/scheduled-backup-modal-form.tsx
https://perconadev.atlassian.net/browse/EVEREST-736
> Fill empty schedule values on restore

- apps/everest/src/hooks/api/backup-storages/__mocks__/useBackupStorages.ts
- apps/everest/src/pages/database-form/database-form.tsx
- apps/everest/src/pages/database-form/steps/backups/backups-schema.ts
- apps/everest/src/pages/database-form/steps/backups/backups.messages.ts
- apps/everest/src/pages/database-form/steps/backups/backups.test.tsx
- apps/everest/src/pages/database-form/steps/backups/backups.tsx
https://perconadev.atlassian.net/browse/EVEREST-698
> EVEREST-698 Added add storage modal when no storages in db wizard

- apps/everest/.e2e/db-cluster/db-wizard/edit-db-cluster/schedules-step.e2e.ts
- apps/everest/src/components/time-selection/time-selection.messages.ts
https://perconadev.atlassian.net/browse/EVEREST-569
> EVEREST-569 Changed scheduled text

- apps/everest/src/hooks/api/db-cluster/useUpdateDbCluster.ts
- apps/everest/src/pages/databases/dbClusterView.messages.ts
- apps/everest/src/pages/databases/expandedRow/ExpandedRow.tsx
https://perconadev.atlassian.net/browse/EVEREST-388
> Everest 388 monitoring info

- apps/everest/src/pages/databases/DbClusterView.tsx
- apps/everest/src/pages/databases/dbClusterView.messages.ts
- apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list.messages.ts
- apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list.tsx
- apps/everest/src/pages/db-cluster-details/backups/scheduled-backups-list/scheduled-backups-list.messages.ts
- apps/everest/src/pages/db-cluster-details/backups/scheduled-backups-list/scheduled-backups-list.tsx
- apps/everest/src/pages/db-cluster-details/db-action-button.tsx
- apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.messages.ts
- apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.tsx
- apps/everest/src/pages/settings/storage-locations/storage-locations.messages.ts
- apps/everest/src/pages/settings/storage-locations/storage-locations.tsx
https://perconadev.atlassian.net/browse/EVEREST-760
> EVEREST-760: add entity names to deletion modals

- apps/everest/src/pages/database-form/steps/first/first-step.tsx
https://perconadev.atlassian.net/browse/EVEREST-753
> fix: keep name if input's dirty

- apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/create-db-cluster.e2e.ts
- apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/steps/basic-information-step.ts
- apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/steps/pitr-step.ts
- apps/everest/src/api/dbClusterApi.ts
- apps/everest/src/hooks/api/db-cluster/useCreateDbCluster.ts
- apps/everest/src/pages/database-form/steps/pitr/pitr-step.tsx
https://perconadev.atlassian.net/browse/EVEREST-625
Do not merge before EVEREST-613
> EVEREST-625 Added pitr for mongodb

- apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
https://perconadev.atlassian.net/browse/EVEREST-628
Do not merge before EVEREST-614
> EVEREST-628 Enabled pitr restore for mongodb

- apps/everest/src/components/app-bar/help-icon/HelpIcon.tsx
https://perconadev.atlassian.net/browse/EVEREST-764
> feat: add issues and forum links

- apps/everest/src/components/auto-complete-auto-fill/auto-complete-auto-fill.tsx
- apps/everest/src/components/schedule-form/schedule-form.tsx
- apps/everest/src/pages/db-cluster-details/backups/backups-list/on-demand-backup-modal/on-demand-backup-fields-wrapper.tsx
- apps/everest/src/pages/db-cluster-details/backups/backups-list/on-demand-backup-modal/on-demand-backup-modal.tsx
- apps/everest/src/pages/db-cluster-details/backups/scheduled-backup-modal/scheduled-backup-modal-form/scheduled-backup-modal-form.tsx
- apps/everest/src/shared-types/dbCluster.types.ts
- packages/ui-lib/src/form/inputs/auto-complete/auto-complete.tsx
- packages/ui-lib/src/form/inputs/auto-complete/auto-complete.types.ts
https://perconadev.atlassian.net/browse/EVEREST-762
> EVEREST-762 Added support for single storage only

- apps/everest/src/pages/database-form/steps/first/first-step.tsx
https://perconadev.atlassian.net/browse/EVEREST-755
> EVEREST-755 fix db version selector

- apps/everest/src/hooks/api/backups/useScheduledBackups.ts
https://perconadev.atlassian.net/browse/EVEREST-782
> EVEREST-782 Fixed disabling pitr when schledule is edited/created

- apps/everest/src/pages/database-form/steps/pitr/pitr-step.tsx
- apps/everest/src/pages/database-form/steps/pitr/pitr.messages.ts
> EVEREST-807 Fixed show storage location name in pitr section

- .github/workflows/ci.yml
- apps/everest/src/hooks/api/db-cluster/__mocks__/useDbCluster.ts
- apps/everest/src/hooks/api/namespaces/__mocks__/useNamespaces.ts
`everest-system` is a more descriptive name than `percona-everest`.
> EVEREST-633 rename restricted namespaces

- apps/everest/.e2e/db-cluster/db-wizard/edit-db-cluster/basic-step.e2e.ts
- apps/everest/.e2e/utils/db-cluster.ts
- apps/everest/src/pages/database-form/steps/first/first-step.tsx
- apps/everest/src/pages/db-cluster-details/db-cluster-details.tsx
https://perconadev.atlassian.net/browse/EVEREST-833
> Everest 833 missing db versions

- apps/everest/src/components/welcome-dialog/welcome-dialog.messages.ts
- apps/everest/src/components/welcome-dialog/welcome-dialog.tsx
https://perconadev.atlassian.net/browse/EVEREST-818
> Everest 818 beta dialog

- apps/everest/.e2e/db-cluster/db-wizard/create-db-cluster/create-db-cluster.e2e.ts
- apps/everest/.e2e/utils/db-wizard.ts
- apps/everest/src/pages/database-form/steps/first/first-step.tsx
- apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.messages.ts
- apps/everest/src/pages/settings/storage-locations/createEditModal/create-edit-form.tsx
https://perconadev.atlassian.net/browse/EVEREST-854
> Everest 854 default nodes

- apps/everest/src/modals/restore-db-modal/restore-db-modal.tsx
> EVEREST-627 enable restore pitr for pg

- apps/everest/src/components/actionable-alert/backups-actionable-alert/BackupsActionableAlert.messages.ts
- apps/everest/src/pages/database-form/steps/backups/backups.messages.ts
- apps/everest/src/pages/db-cluster-details/backups/backups.messages.ts
> EVEREST-759 Changed messages for schedule backups

- apps/everest/src/pages/databases/DbClusterView.tsx
- apps/everest/src/pages/db-cluster-details/backups/backups-list/backups-list.tsx
- apps/everest/src/pages/db-cluster-details/cluster-overview/cards/connection-details.tsx
- apps/everest/src/pages/settings/monitoring-endpoints/monitoring-endpoints.tsx
- apps/everest/src/pages/settings/namespaces/namespaces.tsx
- apps/everest/src/pages/settings/storage-locations/storage-locations.tsx
- packages/ui-lib/src/table/table.tsx
- packages/ui-lib/src/table/table.types.ts
- packages/ui-lib/src/table/usePersistentColumnVisibility.ts
- packages/ui-lib/src/table/usePersistentColumnVisibility.utils.ts
> EVEREST-862 Add column hide state to local storage
